[package]
name = "axum-websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7.9", features = ["ws"] }
tokio = { version = "1.40.1", features = ["full"] }
futures-util = "0.3.31"
